### ISSUE TITLE
No Database File

### ISSUE THREAD

**Issue by Cdeb123** [Phire0/A3FL#2]
\\ No Database Provided

Issue with files
Files are useless without a database
We need a database SQL file uploaded
Other than the SQL everything else is there
Great work on the framework everything else is fine
Some minor script errors but that is to be expected

\\ Summary 

**MISSING SQL FILE**

Add SQL file for people to use

**Comment by phire0** [comment]
Hello @Cdeb123,

I was one of the developers of this framework for the A3FL community when it was up and running. These files are provided as-is from when I resigned from their team.

Unfortunately, I am no longer in possession of the database schema, so I am unable to help in this regard.

My only suggestion would be that you read through the code and try to establish the structure yourself. Alternatively, you could create your own framework and use this as inspiration - trust me, this framework was used by A3PL/A3FL and it did not offer great performance.

Best of luck!
